apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubermetrics-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubermetrics
  template:
    metadata:
      labels:
        app: kubermetrics
    spec:
      containers:
        - name: kubermetrics
          image: kubermetrics/kubermetrics:latest
---
apiVersion: v1
kind: Service
metadata:
  name: kubermetrics-srv
  labels:
    prometheus: cluster-monitoring
    k8s-app: kube-state-metrics
spec:
  selector:
    app: kubermetrics
  type: ClusterIP
  ports:
    - name: kubermetrics
      protocol: TCP
      port: 3080
      targetPort: 3080